USE master
GO
DROP DATABASE  MICONDOMINIO
GO

CREATE DATABASE MICONDOMINIO
GO 

USE MICONDOMINIO
GO

CREATE TABLE TIPOPERSONA
(
	TIPOPERSONA           INTEGER IDENTITY(1,1),
	NOMBRE               VARCHAR(30) NOT NULL,
	CONSTRAINT PK_TPERSONA PRIMARY KEY (TIPOPERSONA)
)
GO



CREATE TABLE PERSONA
(
	PERSONA            INTEGER IDENTITY(1,1),
	TIPOPERSONA           INTEGER NOT NULL,
	NOMBRE               VARCHAR(50) NOT NULL,
	APELLIDO             VARCHAR(50) NOT NULL,
	DNI                  VARCHAR(15) NOT NULL,
	TELEFONO             VARCHAR(50) NOT NULL,
	DIRECCION            VARCHAR(100) NOT NULL,
	EMAIL                VARCHAR(60) NOT NULL,
	CONSTRAINT PK_PERSONA PRIMARY KEY (PERSONA),
	CONSTRAINT FK_PERSONA_TPERSONA FOREIGN KEY (TIPOPERSONA)REFERENCES TIPOPERSONA
)
GO


-- =============================================
-- Carga de Datos
-- =============================================

-- TIPOS DE PERSONAS
INSERT INTO TIPOPERSONA(NOMBRE) VALUES
('INMUEBLE'),
('PROPIETARIO'),
('TRABAJADOR'),
('EX-PROPIETARIO')
GO


-- PERSONAS
INSERT INTO PERSONA(TIPOPERSONA,NOMBRE,APELLIDO,DNI,
TELEFONO,DIRECCION,EMAIL)VALUES
(1,'INMUEBLE','INMUEBLE','11111111','222222222','MI CASA','MI CORREO'),
(2,'SAMUEL','LEON','45768934','997124783','MI CASA','MI CORREO'),
(3,'OSCAR','TRINIDAD','71333584','969370061','MI CASA','MI CORREO'),
(3,'ALONSO','LIPA','78436723','952928804','MI CASA','MI CORREO'),
(3,'GUSTAVO','CORONEL','45768934','784356093','MI CASA','MI CORREO'),
(3,'JOAQUIN','TRINIDAD','71333585','957213381','MI CASA','MI CORREO'),
(4,'DAVID','RIVERA','78436723','910725861','MI CASA','MI CORREO')
