package pe.java.hibernate;
// Generated Nov 18, 2013 3:36:23 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Condominio generated by hbm2java
 */
public class Condominio  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set edificios = new HashSet(0);
     private Set quejas = new HashSet(0);
     private Set administradors = new HashSet(0);

    public Condominio() {
    }

	
    public Condominio(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Condominio(String nombre, String descripcion, Set edificios, Set quejas, Set administradors) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.edificios = edificios;
       this.quejas = quejas;
       this.administradors = administradors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEdificios() {
        return this.edificios;
    }
    
    public void setEdificios(Set edificios) {
        this.edificios = edificios;
    }
    public Set getQuejas() {
        return this.quejas;
    }
    
    public void setQuejas(Set quejas) {
        this.quejas = quejas;
    }
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }




}


