package pe.java.hibernate;
// Generated Nov 18, 2013 3:36:23 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer id;
     private Edificio edificio;
     private String nombre;
     private String descripcion;
     private Set visitas = new HashSet(0);
     private Set residentes = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(Edificio edificio, String nombre, String descripcion) {
        this.edificio = edificio;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Departamento(Edificio edificio, String nombre, String descripcion, Set visitas, Set residentes) {
       this.edificio = edificio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.visitas = visitas;
       this.residentes = residentes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Edificio getEdificio() {
        return this.edificio;
    }
    
    public void setEdificio(Edificio edificio) {
        this.edificio = edificio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getVisitas() {
        return this.visitas;
    }
    
    public void setVisitas(Set visitas) {
        this.visitas = visitas;
    }
    public Set getResidentes() {
        return this.residentes;
    }
    
    public void setResidentes(Set residentes) {
        this.residentes = residentes;
    }




}


