package pe.java.hibernate;
// Generated Nov 18, 2013 3:36:23 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Edificio generated by hbm2java
 */
public class Edificio  implements java.io.Serializable {


     private Integer id;
     private Condominio condominio;
     private String nombre;
     private String descripcion;
     private Set eventos = new HashSet(0);
     private Set departamentos = new HashSet(0);

    public Edificio() {
    }

	
    public Edificio(Condominio condominio, String nombre, String descripcion) {
        this.condominio = condominio;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Edificio(Condominio condominio, String nombre, String descripcion, Set eventos, Set departamentos) {
       this.condominio = condominio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.eventos = eventos;
       this.departamentos = departamentos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Condominio getCondominio() {
        return this.condominio;
    }
    
    public void setCondominio(Condominio condominio) {
        this.condominio = condominio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }




}


