package pe.java.hibernate;
// Generated Nov 18, 2013 3:36:23 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer id;
     private Edificio edificio;
     private String nombre;
     private String descripcion;
     private Set cuotas = new HashSet(0);

    public Evento() {
    }

	
    public Evento(Edificio edificio, String nombre, String descripcion) {
        this.edificio = edificio;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Evento(Edificio edificio, String nombre, String descripcion, Set cuotas) {
       this.edificio = edificio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cuotas = cuotas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Edificio getEdificio() {
        return this.edificio;
    }
    
    public void setEdificio(Edificio edificio) {
        this.edificio = edificio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Set cuotas) {
        this.cuotas = cuotas;
    }




}


