package pe.java.hibernate;
// Generated Nov 18, 2013 3:36:23 PM by Hibernate Tools 3.2.1.GA



/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer id;
     private Cuota cuota;
     private int departamentoId;

    public Pago() {
    }

    public Pago(Cuota cuota, int departamentoId) {
       this.cuota = cuota;
       this.departamentoId = departamentoId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cuota getCuota() {
        return this.cuota;
    }
    
    public void setCuota(Cuota cuota) {
        this.cuota = cuota;
    }
    public int getDepartamentoId() {
        return this.departamentoId;
    }
    
    public void setDepartamentoId(int departamentoId) {
        this.departamentoId = departamentoId;
    }




}


