package pe.java.hibernate;
// Generated Nov 18, 2013 3:36:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Queja generated by hbm2java
 */
public class Queja  implements java.io.Serializable {


     private Integer id;
     private Condominio condominio;
     private String nombre;
     private String descripcion;
     private Date fecha;

    public Queja() {
    }

    public Queja(Condominio condominio, String nombre, String descripcion, Date fecha) {
       this.condominio = condominio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Condominio getCondominio() {
        return this.condominio;
    }
    
    public void setCondominio(Condominio condominio) {
        this.condominio = condominio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


