package pe.java.hibernate;
// Generated Nov 18, 2013 3:36:23 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer id;
    private String correo;
    private String clave;
    private String nombres;
    private String apellidoPat;
    private String apellidoMat;
    private String dni;
    private Set administradors = new HashSet(0);
    private Set residentes = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String correo, String clave, String nombres, String apellidoPat, String apellidoMat, String dni) {
        this.correo = correo;
        this.clave = clave;
        this.nombres = nombres;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.dni = dni;
    }

    public Usuario(String correo, String clave, String nombres, String apellidoPat, String apellidoMat, String dni, Set administradors, Set residentes) {
        this.correo = correo;
        this.clave = clave;
        this.nombres = nombres;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.dni = dni;
        this.administradors = administradors;
        this.residentes = residentes;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidoPat() {
        return this.apellidoPat;
    }

    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }

    public String getApellidoMat() {
        return this.apellidoMat;
    }

    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public Set getAdministradors() {
        return this.administradors;
    }

    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }

    public Set getResidentes() {
        return this.residentes;
    }

    public void setResidentes(Set residentes) {
        this.residentes = residentes;
    }
}
